services:
  rental_mobil:
    build: .
    container_name: rental_mobil
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - app_network

  nginx_rental_mobil:
    image: nginx:alpine
    container_name: nginx_rental_mobil
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - rental_mobil
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
